language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
install:
  - npm install
script:
  - npm run build
after_success:
  - "./deploy.sh"

